### ISSUE TITLE
Preecnher sessão "Contribuidoras"

### ISSUE THREAD

**Issue by cecivieira** [pyladies-brazil/introducao-python#10]
No README.md preencher a sessão de contribuidoras com todas as mulheres que contribuiram para o desenvolvimento do material.

Fontes sugeridas: 
- [Atas das reuniões do "GT Ciração de Material"](https://github.com/pyladies-brazil/organizacao/issues?q=label%3Amateriais+is%3Aclosed)
- [Thread do slack sobre criação de slides](https://pyladies.slack.com/archives/C019V220SRF/p1599871173005400)
- [Lista de mini vídeos](https://docs.google.com/spreadsheets/d/1vOMtGv92r0b7l6DjsqJy0YvTwP3zTUtddxoj5ME7JKQ/edit?usp=sharing)

Inspiração:
![image](https://user-images.githubusercontent.com/30605862/113214534-01ca3480-9250-11eb-93ba-8246c4370522.png)
[Repositório do lesspass](https://github.com/lesspass/lesspass)

**Comment by jtemporal** [comment]
Oie! Posso cuidar dessa! 😉

**Comment by jtemporal** [comment]
@cecivieira Ta feito o przinho 😉
